In [1]:
import xlrd
import pandas as pd

# Open the Excel file
book = xlrd.open_workbook("IAC_Database_20231107.xls")

# Get the sheet names
sheet_names = book.sheet_names()

# Create a dictionary to store DataFrames
dfs = {}

# Loop through each sheet and create a DataFrame
for sheet_name in sheet_names:
    sheet = book.sheet_by_name(sheet_name)
    df = pd.DataFrame([sheet.row_values(i) for i in range(1, sheet.nrows)])  # Skip the header row
    header = [sheet.cell_value(0, j) for j in range(sheet.ncols)]  # Get header values
    df.columns = header  # Set column names
    dfs[sheet_name] = df  # Store DataFrame in the dictionary

In [2]:
for i in dfs:
    print(i)

ASSESS
RECC1
RECC2
RECC3
RECC4
RECC5
RECC6
Terms

In [3]:
# Iterate through the dictionary and create new DataFrames with names appended with "_df"
for sheet_name, df in dfs.items():
    new_df_name = f"{sheet_name}_df"
    globals()[new_df_name] = df  # Create a new DataFrame with the specified name
    print(f"Created DataFrame: {new_df_name}")

# Now you have new DataFrames with names like "ASSESS_df", "RECC1_df", etc.

Created DataFrame: ASSESS_df
Created DataFrame: RECC1_df
Created DataFrame: RECC2_df
Created DataFrame: RECC3_df
Created DataFrame: RECC4_df
Created DataFrame: RECC5_df
Created DataFrame: RECC6_df
Created DataFrame: Terms_df

In [4]:
ASSESS_df

,ID,CENTER,FY,SIC,NAICS,STATE,SALES,EMPLOYEES,PLANT_AREA,PRODUCTS,...,W2_plant_cost,W2_plant_usage,W3_plant_cost,W3_plant_usage,W4_plant_cost,W4_plant_usage,W5_plant_cost,W5_plant_usage,W6_plant_cost,W6_plant_usage
0,AM0001,AM,1987.0,3671.0,,TX,33900000.0,206.0,,MICRO & MINI COMPUTERS,...,,,,,,,,,,
1,AM0002,AM,1987.0,2761.0,,TX,25000000.0,156.0,,BUSINESS FORMS,...,,,,,,,,,,
2,AM0003,AM,1987.0,3494.0,,TX,15000000.0,200.0,,SAFETY JOINTS & VALVES,...,,,,,,,,,,
3,AM0004,AM,1987.0,3713.0,,TX,4200000.0,75.0,,TRUCKS BEDS & TRAILERS,...,,,,,,,,,,
4,AM0005,AM,1987.0,2024.0,,TX,12000000.0,39.0,,ICE CREAM,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20976,WV0650,WV,2023.0,2821.0,325211.0,WV,5000000.0,78.0,350000.0,Polymer Resins,...,,,,,,,,,,
20977,WV0651,WV,2023.0,3581.0,333310.0,WV,20680000.0,94.0,75100.0,Vending machines,...,,,,,,,,,,
20978,WV0652,WV,2023.0,3089.0,326199.0,WV,45000000.0,250.0,1000000.0,Plastic Products,...,,,,,,,,,,
20979,WV0653,WV,2023.0,3069.0,326299.0,OH,99000000.0,313.0,375000.0,Insulation glass rubber,...,,,,,,,,,,
20980,WV0654,WV,2023.0,3537.0,336120.0,VA,99000000.0,350.0,300000.0,Medium Duty Trucks,...,,,,,,,,,,

In [5]:
ASSESS_df.describe()

                 FY        NUMARS
count  20981.000000  20981.000000
mean    2003.006673      7.463467
std       11.107566      2.841753
min     1981.000000      1.000000
25%     1995.000000      5.000000
50%     2002.000000      7.000000
75%     2012.000000      9.000000
max     2024.000000     33.000000

In [6]:
RECC1_df

,SUPERID,ID,AR_NUMBER,APPCODE,ARC2,IMPSTATUS,IMPCOST,PSOURCCODE,PCONSERVED,PSOURCONSV,...,QCONSERVED,QSOURCONSV,QSAVED,REBATE,INCREMNTAL,FY,IC_CAPITAL,IC_OTHER,PAYBACK,BPTOOL
0,AM000101,AM0001,1.0,,2.8114,N,15000.0,E1,,,...,,,,N,N,1987.0,,,8.205689,
1,AM000102,AM0001,2.0,,2.7142,N,189.0,E1,7034.0,72.0,...,,,,N,N,1987.0,,,0.285068,
2,AM000103,AM0001,3.0,,2.7111,N,398.0,E1,10258.0,105.0,...,,,,N,N,1987.0,,,0.418947,
3,AM000104,AM0001,4.0,,2.7447,I,354.0,E1,10844.0,111.0,...,,,,N,N,1987.0,,,0.650735,
4,AM000105,AM0001,5.0,,2.7233,N,15.0,E1,4982.0,51.0,...,,,,N,N,1987.0,,,0.055556,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,GT041101,GT0411,1.0,,2.6232,I,,E1,43376.0,445.0,...,,,,N,N,1990.0,,,,
29996,GT041102,GT0411,2.0,,2.7142,I,48.0,E1,4982.0,51.0,...,,,,N,N,1990.0,,,0.122137,
29997,GT041103,GT0411,3.0,,2.6212,I,,E1,11137.0,114.0,...,,,,N,N,1990.0,,,,
29998,GT041104,GT0411,4.0,,2.4133,I,678.0,E1,6448.0,66.0,...,,,,N,N,1990.0,,,1.272045,
29999,GT041105,GT0411,5.0,,2.4111,N,,E1,7913.0,81.0,...,,,,N,N,1990.0,,,,

In [7]:
import pandas as pd
import numpy as np

# Assuming ASSESS_df is your DataFrame
# Replace whitespace or other non-null values with NaN
ASSESS_df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

# Check for empty cells in the entire DataFrame
empty_cells = ASSESS_df.isna()

# If you want to count the number of empty cells in each column, you can use the sum() function
empty_cells_count = empty_cells.sum()

# Print the count of empty cells in each column
print(empty_cells_count)

ID                     0
CENTER                 0
FY                     0
SIC                    1
NAICS              10970
STATE                 11
SALES                127
EMPLOYEES             15
PLANT_AREA          4093
PRODUCTS               5
PRODUNITS           3647
PRODLEVEL           1278
PRODHOURS             92
NUMARS                 0
EC_plant_cost         41
EC_plant_usage        44
ED_plant_cost       7860
ED_plant_usage      7807
EF_plant_cost      11976
E2_plant_cost       3761
E2_plant_usage      3762
E3_plant_cost      19906
E3_plant_usage     19908
E4_plant_cost      20894
E4_plant_usage     20894
E5_plant_cost      20120
E5_plant_usage     20121
E6_plant_cost      20834
E6_plant_usage     20834
E7_plant_cost      20705
E7_plant_usage     20705
E8_plant_cost      20876
E8_plant_usage     20876
E9_plant_cost      20744
E9_plant_usage     20721
E10_plant_cost     20979
E10_plant_usage    20979
E11_plant_cost     20851
E11_plant_usage    20858
E12_plant_cost     20725
E12_plant_usage    20728
W0_plant_cost      19461
W0_plant_usage     19461
W1_plant_cost      17271
W1_plant_usage     17262
W2_plant_cost      20205
W2_plant_usage     20188
W3_plant_cost      20233
W3_plant_usage     20208
W4_plant_cost      18463
W4_plant_usage     18508
W5_plant_cost      20711
W5_plant_usage     20672
W6_plant_cost      20926
W6_plant_usage     20862
dtype: int64

In [8]:
dataframes = [RECC1_df, RECC2_df, RECC3_df, RECC4_df, RECC5_df, RECC6_df]

# Concatenate DataFrames vertically
RECC_df = pd.concat(dataframes, axis=0, ignore_index=True)

In [9]:
RECC_df

,SUPERID,ID,AR_NUMBER,APPCODE,ARC2,IMPSTATUS,IMPCOST,PSOURCCODE,PCONSERVED,PSOURCONSV,...,QCONSERVED,QSOURCONSV,QSAVED,REBATE,INCREMNTAL,FY,IC_CAPITAL,IC_OTHER,PAYBACK,BPTOOL
0,AM000101,AM0001,1.0,,2.8114,N,15000.0,E1,,,...,,,,N,N,1987.0,,,8.205689,
1,AM000102,AM0001,2.0,,2.7142,N,189.0,E1,7034.0,72.0,...,,,,N,N,1987.0,,,0.285068,
2,AM000103,AM0001,3.0,,2.7111,N,398.0,E1,10258.0,105.0,...,,,,N,N,1987.0,,,0.418947,
3,AM000104,AM0001,4.0,,2.7447,I,354.0,E1,10844.0,111.0,...,,,,N,N,1987.0,,,0.650735,
4,AM000105,AM0001,5.0,,2.7233,N,15.0,E1,4982.0,51.0,...,,,,N,N,1987.0,,,0.055556,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156635,WV065413,WV0654,13.0,,2.4157,,1500.0,EC,15555.0,,...,,,,N,N,2023.0,1500.0,,,MM+
156636,WV065414,WV0654,14.0,,2.4151,,1370.0,EC,7291.0,,...,,,,N,N,2023.0,,1370.0,,MEASUR
156637,WV065415,WV0654,15.0,,2.4221,,970.0,EC,2562.0,,...,,,,N,N,2023.0,430.0,540.0,,AM+
156638,WV065416,WV0654,16.0,,2.2511,,98.0,E2,12.0,,...,,,,N,N,2023.0,75.0,23.0,,SSTS
156639,WV065417,WV0654,17.0,,2.4231,,240.0,EC,1971.0,,...,,,,N,N,2023.0,,240.0,,AM+

In [10]:
RECC_df['IMPSTATUS'] = RECC_df['IMPSTATUS'].replace('', 'P')

In [11]:
RECC_df

,SUPERID,ID,AR_NUMBER,APPCODE,ARC2,IMPSTATUS,IMPCOST,PSOURCCODE,PCONSERVED,PSOURCONSV,...,QCONSERVED,QSOURCONSV,QSAVED,REBATE,INCREMNTAL,FY,IC_CAPITAL,IC_OTHER,PAYBACK,BPTOOL
0,AM000101,AM0001,1.0,,2.8114,N,15000.0,E1,,,...,,,,N,N,1987.0,,,8.205689,
1,AM000102,AM0001,2.0,,2.7142,N,189.0,E1,7034.0,72.0,...,,,,N,N,1987.0,,,0.285068,
2,AM000103,AM0001,3.0,,2.7111,N,398.0,E1,10258.0,105.0,...,,,,N,N,1987.0,,,0.418947,
3,AM000104,AM0001,4.0,,2.7447,I,354.0,E1,10844.0,111.0,...,,,,N,N,1987.0,,,0.650735,
4,AM000105,AM0001,5.0,,2.7233,N,15.0,E1,4982.0,51.0,...,,,,N,N,1987.0,,,0.055556,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156635,WV065413,WV0654,13.0,,2.4157,P,1500.0,EC,15555.0,,...,,,,N,N,2023.0,1500.0,,,MM+
156636,WV065414,WV0654,14.0,,2.4151,P,1370.0,EC,7291.0,,...,,,,N,N,2023.0,,1370.0,,MEASUR
156637,WV065415,WV0654,15.0,,2.4221,P,970.0,EC,2562.0,,...,,,,N,N,2023.0,430.0,540.0,,AM+
156638,WV065416,WV0654,16.0,,2.2511,P,98.0,E2,12.0,,...,,,,N,N,2023.0,75.0,23.0,,SSTS
156639,WV065417,WV0654,17.0,,2.4231,P,240.0,EC,1971.0,,...,,,,N,N,2023.0,,240.0,,AM+

In [12]:
merged_df = pd.merge(RECC_df, ASSESS_df, on='ID', how='left')

In [13]:
merged_df

,SUPERID,ID,AR_NUMBER,APPCODE,ARC2,IMPSTATUS,IMPCOST,PSOURCCODE,PCONSERVED,PSOURCONSV,...,W2_plant_cost,W2_plant_usage,W3_plant_cost,W3_plant_usage,W4_plant_cost,W4_plant_usage,W5_plant_cost,W5_plant_usage,W6_plant_cost,W6_plant_usage
0,AM000101,AM0001,1.0,,2.8114,N,15000.0,E1,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AM000102,AM0001,2.0,,2.7142,N,189.0,E1,7034.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AM000103,AM0001,3.0,,2.7111,N,398.0,E1,10258.0,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AM000104,AM0001,4.0,,2.7447,I,354.0,E1,10844.0,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AM000105,AM0001,5.0,,2.7233,N,15.0,E1,4982.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156635,WV065413,WV0654,13.0,,2.4157,P,1500.0,EC,15555.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156636,WV065414,WV0654,14.0,,2.4151,P,1370.0,EC,7291.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156637,WV065415,WV0654,15.0,,2.4221,P,970.0,EC,2562.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156638,WV065416,WV0654,16.0,,2.2511,P,98.0,E2,12.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156639,WV065417,WV0654,17.0,,2.4231,P,240.0,EC,1971.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd
import math

# Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Frequency Table and Plot"),

    # Input for SIC number
    html.Label("Enter SIC Number:"),
    dcc.Input(id='sic-input', type='number', value=2761),

    # Output for plot
    dcc.Graph(id='output-plot')
])

# Callback to update frequency table and plot based on input SIC
@app.callback(
    [Output('output-plot', 'figure')],
    [Input('sic-input', 'value')]
)
def update_output(sic_input):
    if sic_input is None or sic_input not in ASSESS_df['SIC'].unique():
        return px.scatter(),  # Return a default scatter plot if SIC is not valid

    # Filter DataFrame based on input SIC
    filtered_df = ASSESS_df[ASSESS_df['SIC'] == sic_input][['EC_plant_usage']]

    # Calculate every 33% and get values as a NumPy array
    quartiles = filtered_df['EC_plant_usage'].quantile([1/3, 2/3,1]).values

    # Plot the figure
    fig = px.histogram(
        filtered_df,
        x='EC_plant_usage',
        nbins=len(range(0, int(max(filtered_df['EC_plant_usage'])) + 1000000, 1000000)),
        title='Frequency of EC_plant_usage',
        opacity=0.7,  # Adjust the opacity for better visibility of outlined bins
        barmode='overlay',  # Set barmode to 'overlay' for outlined bins
        color_discrete_sequence=['black']
    )

    fig.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    bins = range(0, int(filtered_df['EC_plant_usage'].max()) + 1000000, 1000000)

    # Create a new column 'bin' based on the bins
    filtered_df['bin'] = pd.cut(filtered_df['EC_plant_usage'], bins=bins)

    # Create a frequency DataFrame
    frequency_df = filtered_df['bin'].value_counts().reset_index()
    # Add shaded regions for every 33%
    fig.add_shape(
        type='rect',
        x0=0,
        x1=quartiles[0],
        y0=0,
        y1=1.2*int(frequency_df['count'].max()),
        fillcolor='rgba(39,43,84, 0.5)',  
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )

    fig.add_shape(
        type='rect',
        x0=quartiles[0],
        x1=quartiles[1],
        y0=0,
        y1=1.2*int(frequency_df['count'].max()),
        fillcolor='rgba(195,46,91, 0.5)',  
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )

    fig.add_shape(
        type='rect',
        x0=quartiles[1],
        x1=math.ceil(int(quartiles[2]) / 1000000) * 1000000,
        y0=0,
        y1=1.2*int(frequency_df['count'].max()),
        fillcolor='rgba(235,125,39, 0.5)',  
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )

    return fig,

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

Address already in use
Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.

AttributeError: 'tuple' object has no attribute 'tb_frame'

In [ ]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd
import math
import plotly.graph_objs as go


# Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Frequency Table and Plot"),

    # Input for SIC number
    html.Label("Enter SIC Number:"),
    dcc.Input(id='sic-input', type='number', value=2761),

    # Output for plot
    dcc.Graph(id='output-plot')
])

# Callback to update frequency table and plot based on input SIC
@app.callback(
    [Output('output-plot', 'figure')],
    [Input('sic-input', 'value')]
)
def update_output(sic_input):
    if sic_input is None or sic_input not in ASSESS_df['SIC'].unique():
        return px.scatter(),  # Return a default scatter plot if SIC is not valid

    # Filter DataFrame based on input SIC
    filtered_df = ASSESS_df[ASSESS_df['SIC'] == sic_input][['EC_plant_usage']]

    # Calculate every 33% and get values as a NumPy array
    quartiles = filtered_df['EC_plant_usage'].quantile([1/3, 2/3,1]).values

    # Plot the figure
    fig = px.histogram(
        filtered_df,
        x='EC_plant_usage',
        nbins=len(range(0, int(max(filtered_df['EC_plant_usage'])) + 1000000, 1000000)),
        title='Frequency of EC_plant_usage',
        opacity=0.7,  # Adjust the opacity for better visibility of outlined bins
        barmode='overlay',  # Set barmode to 'overlay' for outlined bins
        color_discrete_sequence=['black'],
        marginal="box", # or violin, rug, box
        hover_data=[filtered_df['EC_plant_usage']]
    )

    fig.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    bins = range(0, int(filtered_df['EC_plant_usage'].max()) + 1000000, 1000000)

    # Create a new column 'bin' based on the bins
    filtered_df['bin'] = pd.cut(filtered_df['EC_plant_usage'], bins=bins)

    # Create a frequency DataFrame
    frequency_df = filtered_df['bin'].value_counts().reset_index()
    # Add shaded regions for every 33%
    fig.add_shape(
        type='rect',
        x0=0,
        x1=quartiles[0],
        y0=0,
        y1=1.3*int(frequency_df['count'].max()),
        fillcolor='rgba(39,43,84, 0.5)',  
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )

    fig.add_shape(
        type='rect',
        x0=quartiles[0],
        x1=quartiles[1],
        y0=0,
        y1=1.3*int(frequency_df['count'].max()),
        fillcolor='rgba(195,46,91, 0.5)',  
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )

    fig.add_shape(
        type='rect',
        x0=quartiles[1],
        x1=math.ceil(int(quartiles[2]) / 1000000) * 1000000,
        y0=0,
        y1=1.3*int(frequency_df['count'].max()),
        fillcolor='rgba(235,125,39, 0.5)',  
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    # Add hover labels for each 33% and 66% line with specified colors
    for q, label, color in zip(quartiles[:2], ['33%', '66%'], [(239,227,2), (126, 201, 76)]):
        fig.add_annotation(
            x=q,
            y=int(frequency_df['count'].max()),
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )



    return fig,

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

In [ ]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd
import math
import plotly.graph_objs as go


# Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Frequency Table and Plot"),

    # Input for SIC number
    html.Label("Enter SIC Number:"),
    dcc.Input(id='sic-input', type='number', value=2761),

    # Output for plot
    dcc.Graph(id='output-plot')
])

# Callback to update frequency table and plot based on input SIC
@app.callback(
    [Output('output-plot', 'figure')],
    [Input('sic-input', 'value')]
)
def update_output(sic_input):
    if sic_input is None or sic_input not in ASSESS_df['SIC'].unique():
        return px.scatter(),  # Return a default scatter plot if SIC is not valid

    # Filter DataFrame based on input SIC
    filtered_df = ASSESS_df[ASSESS_df['SIC'] == sic_input][['E2_plant_usage']]
    print(filtered_df.describe())

    # Calculate every 33% and get values as a NumPy array
    quartiles = filtered_df['E2_plant_usage'].quantile([1/3, 2/3,1]).values

    # Plot the figure
    fig = px.histogram(
        filtered_df,
        x='E2_plant_usage',
        title='Frequency of Yearly natural gas consumption (MMBtu)',
        opacity=0.7,
        barmode='overlay',
        color_discrete_sequence=['black'],
        marginal="box",
        hover_data=[filtered_df['E2_plant_usage']],
        range_x=[0, math.ceil(max(filtered_df['E2_plant_usage'] / 10000)) * 10000]  # Set the x-axis range to start from zero
    )

    fig.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    bins = range(0, int(filtered_df['E2_plant_usage'].max()) + 10000, 10000)

    # Create a new column 'bin' based on the bins
    filtered_df['bin'] = pd.cut(filtered_df['E2_plant_usage'], bins=bins)

    # Create a frequency DataFrame
    frequency_df = filtered_df['bin'].value_counts().reset_index()
    # Add shaded regions for every 33%
    fig.add_shape(
        type='rect',
        x0=0,
        x1=quartiles[0],
        y0=0,
        y1=1.3*int(frequency_df['count'].max()),
        fillcolor='rgba(39,43,84, 0.5)',  
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )

    fig.add_shape(
        type='rect',
        x0=quartiles[0],
        x1=quartiles[1],
        y0=0,
        y1=1.3*int(frequency_df['count'].max()),
        fillcolor='rgba(195,46,91, 0.5)',  
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )

    fig.add_shape(
        type='rect',
        x0=quartiles[1],
        x1=math.ceil(int(quartiles[2]) / 10000) * 10000,
        y0=0,
        y1=1.3*int(frequency_df['count'].max()),
        fillcolor='rgba(235,125,39, 0.5)',  
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    # Add hover labels for each 33% and 66% line with specified colors
    for q, label, color in zip(quartiles[:2], ['33%', '66%'], [(239,227,2), (126, 201, 76)]):
        fig.add_annotation(
            x=q,
            y=int(frequency_df['count'].max()),
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )



    return fig,

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

In [ ]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd
import math
import plotly.graph_objs as go


# Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Frequency Table and Plot"),

    # Dropdown for SIC number
    dcc.Dropdown(sorted(ASSESS_df['SIC'].unique()), id='sic-input'),
    
    # Output for plot 1
    dcc.Graph(id='output-plot-1'),

    # Output for plot 2
    dcc.Graph(id='output-plot-2')
])

# Callback to update frequency table and plot based on input SIC
@app.callback(
    [Output('output-plot-1', 'figure'),
     Output('output-plot-2', 'figure')],
    [Input('sic-input', 'value')]
)
def update_output(sic_input):
    if sic_input is None or sic_input not in ASSESS_df['SIC'].unique():
        return px.scatter(), px.scatter()  # Return default scatter plots if SIC is not valid

    # Filter DataFrame based on input SIC for Plot 1
    filtered_df_1 = ASSESS_df[ASSESS_df['SIC'] == sic_input][['EC_plant_usage']]
    filtered_df_1['EC_plant_usage'] = filtered_df_1['EC_plant_usage'].fillna(0).astype(int)
    print(filtered_df_1)
    # Calculate every 33% and get values as a NumPy array
    quartiles_1 = filtered_df_1['EC_plant_usage'].quantile([1/3, 2/3, 1]).values

    # Plot for Plot 1
    fig_1 = px.histogram(
        filtered_df_1,
        x='EC_plant_usage',
        title='Frequency of Yearly electricity consumption (kWh)',
        opacity=0.7,
        barmode='overlay',
        color_discrete_sequence=['black'],
        marginal="box",
        hover_data=[filtered_df_1['EC_plant_usage']],
        range_x=[0, math.ceil(max(filtered_df_1['EC_plant_usage'] / 1000000)) * 1000000],
        nbins=len(range(0, math.ceil(max(filtered_df_1['EC_plant_usage'] / 1000000)) * 1000000, 1000000))
    )

    fig_1.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    bins_1 = range(0, math.ceil(max(filtered_df_1['EC_plant_usage'] / 1000000)) * 1000000, 1000000)

    # Create a new column 'bin' based on the bins
    filtered_df_1['bin'] = pd.cut(filtered_df_1['EC_plant_usage'], bins=bins_1)

    # Create a frequency DataFrame
    frequency_df_1 = filtered_df_1['bin'].value_counts().reset_index()
    # Add shaded regions for every 33%
    fig_1.add_shape(
        type='rect',
        x0=0,
        x1=quartiles_1[0],
        y0=0,
        y1=1.3*int(frequency_df_1['count'].max()),
        fillcolor='rgba(39,43,84, 0.5)',
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )

    fig_1.add_shape(
        type='rect',
        x0=quartiles_1[0],
        x1=quartiles_1[1],
        y0=0,
        y1=1.3*int(frequency_df_1['count'].max()),
        fillcolor='rgba(195,46,91, 0.5)',
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )

    fig_1.add_shape(
        type='rect',
        x0=quartiles_1[1],
        x1=math.ceil(int(quartiles_1[2]) / 1000000) * 1000000,
        y0=0,
        y1=1.3*int(frequency_df_1['count'].max()),
        fillcolor='rgba(235,125,39, 0.5)',
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    # Add hover labels for each 33% and 66% line with specified colors
    for q, label, color in zip(quartiles_1[:2], ['33%', '66%'], [(239,227,2), (126, 201, 76)]):
        fig_1.add_annotation(
            x=q,
            y=int(frequency_df_1['count'].max()),
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )
    fig_1.show()

    # Filter DataFrame based on input SIC for Plot 2
    filtered_df_2 = ASSESS_df[ASSESS_df['SIC'] == sic_input][['E2_plant_usage']]
    filtered_df_2['E2_plant_usage'] = filtered_df_2['E2_plant_usage'].fillna(0).astype(int)
    print(filtered_df_2)
    # Calculate every 33% and get values as a NumPy array
    quartiles_2 = filtered_df_2['E2_plant_usage'].quantile([1/3, 2/3, 1]).values

    # Plot for Plot 2
    fig_2 = px.histogram(
        filtered_df_2,
        x='E2_plant_usage',
        title='Frequency of Yearly natural gas consumption (MMBtu)',
        opacity=0.7,
        barmode='overlay',
        color_discrete_sequence=['black'],
        marginal="box",
        hover_data=[filtered_df_2['E2_plant_usage']],
        range_x=[0, math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000],
        nbins=len(range(0, math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000, 1000))
    )
    fig_2.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    bins_2 = range(0, math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000, 1000)

    # Create a new column 'bin' based on the bins
    filtered_df_2['bin'] = pd.cut(filtered_df_2['E2_plant_usage'], bins=bins_2)
    print(filtered_df_2)
    # Create a frequency DataFrame
    frequency_df_2 = filtered_df_2['bin'].value_counts().reset_index()
    print(frequency_df_2)
    # Add shaded regions for every 33%
    fig_2.add_shape(
        type='rect',
        x0=0,
        x1=int(quartiles_2[0]),
        y0=0,
        y1=1.3*int(frequency_df_2['count'].max()),
        fillcolor='rgba(39,43,84, 0.5)',
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )

    fig_2.add_shape(
        type='rect',
        x0=int(quartiles_2[0]),
        x1=int(quartiles_2[1]),
        y0=0,
        y1=1.3*int(frequency_df_2['count'].max()),
        fillcolor='rgba(195,46,91, 0.5)',
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )

    fig_2.add_shape(
        type='rect',
        x0=int(quartiles_2[1]),
        x1=int(math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000),
        y0=0,
        y1=1.3*int(frequency_df_2['count'].max()),
        fillcolor='rgba(235,125,39, 0.5)',
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    # Add hover labels for each 33% and 66% line with specified colors
    for q, label, color in zip(quartiles_2[:2], ['33%', '66%'], [(239,227,2), (126, 201, 76)]):
        fig_2.add_annotation(
            x=q,
            y=int(frequency_df_2['count'].max()),
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )
    
    return fig_1, fig_2

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

In [ ]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd
import math
import plotly.graph_objs as go


# Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Frequency Table and Plot"),

    # Dropdown for SIC number
    dcc.Dropdown(sorted(ASSESS_df['SIC'].unique()), id='sic-input'),
    
    # Output for plot 1
    dcc.Graph(id='output-plot-1'),

    # Output for plot 2
    dcc.Graph(id='output-plot-2')
])

# Callback to update frequency table and plot based on input SIC
@app.callback(
    [Output('output-plot-1', 'figure'),
     Output('output-plot-2', 'figure')],
    [Input('sic-input', 'value')]
)
def update_output(sic_input):
    if sic_input is None or sic_input not in ASSESS_df['SIC'].unique():
        return px.scatter(), px.scatter()  # Return default scatter plots if SIC is not valid

    # Filter DataFrame based on input SIC for Plot 1
    filtered_df_1 = ASSESS_df[ASSESS_df['SIC'] == sic_input][['EC_plant_usage']]
    filtered_df_1['EC_plant_usage'] = filtered_df_1['EC_plant_usage'].fillna(0).astype(int)
    # Calculate every 33% and get values as a NumPy array
    quartiles_1 = filtered_df_1['EC_plant_usage'].quantile([1/3, 2/3, 1]).values

    # Plot for Plot 1
    fig_1 = px.histogram(
        filtered_df_1,
        x='EC_plant_usage',
        title='Frequency of Yearly electricity consumption (kWh)',
        opacity=0.7,
        barmode='overlay',
        color_discrete_sequence=['black'],
        marginal="box",
        hover_data=[filtered_df_1['EC_plant_usage']],
        range_x=[0, math.ceil(max(filtered_df_1['EC_plant_usage'] / 1000000)) * 1000000],
        nbins=len(range(0, math.ceil(max(filtered_df_1['EC_plant_usage'] / 1000000)) * 1000000, 1000000))
    )

    fig_1.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    # Create the frequency table using pd.cut()
    binsize=1000000
    frequency_table_1 = pd.cut(filtered_df_1['EC_plant_usage'], bins=range(0, filtered_df_1['EC_plant_usage'].max() + binsize, binsize))

    # Count the occurrences in each bin
    frequency_counts_1 = frequency_table_1.value_counts().sort_index()

    # Find the maximum count
    max_count_1 = frequency_counts_1.max()
    
    # Add shaded regions for every 33%
    fig_1.add_shape(
        type='rect',
        x0=0,
        x1=quartiles_1[0],
        y0=0,
        y1=1.3*max_count_1,
        fillcolor='rgba(39,43,84, 0.5)',
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )

    fig_1.add_shape(
        type='rect',
        x0=quartiles_1[0],
        x1=quartiles_1[1],
        y0=0,
        y1=1.3*max_count_1,
        fillcolor='rgba(195,46,91, 0.5)',
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )

    fig_1.add_shape(
        type='rect',
        x0=quartiles_1[1],
        x1=math.ceil(int(quartiles_1[2]) / 1000000) * 1000000,
        y0=0,
        y1=1.3*max_count_1,
        fillcolor='rgba(235,125,39, 0.5)',
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    # Add hover labels for each 33% and 66% line with specified colors
    for q, label, color in zip(quartiles_1[:2], ['33%', '66%'], [(239,227,2), (126, 201, 76)]):
        fig_1.add_annotation(
            x=q,
            y=max_count_1,
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )

    # Filter DataFrame based on input SIC for Plot 2
    filtered_df_2 = ASSESS_df[ASSESS_df['SIC'] == sic_input][['E2_plant_usage']]
    filtered_df_2['E2_plant_usage'] = filtered_df_2['E2_plant_usage'].fillna(0).astype(int)
    # Calculate every 33% and get values as a NumPy array
    quartiles_2 = filtered_df_2['E2_plant_usage'].quantile([1/3, 2/3, 1]).values

    # Plot for Plot 2
    fig_2 = px.histogram(
        filtered_df_2,
        x='E2_plant_usage',
        title='Frequency of Yearly natural gas consumption (MMBtu)',
        opacity=0.7,
        barmode='overlay',
        color_discrete_sequence=['black'],
        marginal="box",
        hover_data=[filtered_df_2['E2_plant_usage']],
        range_x=[0, math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000],
        nbins=len(range(0, math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000, 1000))
    )
    fig_2.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    # Create the frequency table using pd.cut()
    binsize=1000
    frequency_table_2 = pd.cut(filtered_df_2['E2_plant_usage'], bins=range(0, filtered_df_2['E2_plant_usage'].max() + binsize, binsize))

    # Count the occurrences in each bin
    frequency_counts_2 = frequency_table_2.value_counts().sort_index()

    # Find the maximum count
    max_count_2 = frequency_counts_2.max()

    # Add shaded regions for every 33%
    fig_2.add_shape(
        type='rect',
        x0=0,
        x1=int(quartiles_2[0]),
        y0=0,
        y1=1.3*max_count_2,
        fillcolor='rgba(39,43,84, 0.5)',
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )

    fig_2.add_shape(
        type='rect',
        x0=int(quartiles_2[0]),
        x1=int(quartiles_2[1]),
        y0=0,
        y1=1.3*max_count_2,
        fillcolor='rgba(195,46,91, 0.5)',
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )

    fig_2.add_shape(
        type='rect',
        x0=int(quartiles_2[1]),
        x1=int(math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000),
        y0=0,
        y1=1.3*max_count_2,
        fillcolor='rgba(235,125,39, 0.5)',
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    # Add hover labels for each 33% and 66% line with specified colors
    for q, label, color in zip(quartiles_2[:2], ['33%', '66%'], [(239,227,2), (126, 201, 76)]):
        fig_2.add_annotation(
            x=q,
            y=max_count_2,
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )
    
    return fig_1, fig_2

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

In [2]:
import dash
from dash import dcc, html, dash_table
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd
import math

# Load your dataframes
ASSESS_df = pd.read_csv('ASSESS_df.csv')
RECC_df = pd.read_csv('RECC_df.csv')
ISADS = pd.read_csv('ISAD.csv')

# Dash app
app = dash.Dash(__name__)
server = app.server

# Custom CSS styling
app.css.append_css({
    'external_url': 'https://codepen.io/chriddyp/pen/bWLwgP.css'
})

# Layout of the app
app.layout = html.Div(style={'backgroundColor': '#f2f2f2', 'padding': '20px'}, children=[
    html.H1("Frequency Table and Plot", style={'color': '#333333'}),

    # Dropdown for SIC number
    dcc.Dropdown(sorted(ASSESS_df['SIC'].unique()), id='sic-input'),

    # Output for plot 1
    dcc.Graph(id='output-plot-1'),

    # Output for plot 2
    dcc.Graph(id='output-plot-2'),

    dash_table.DataTable(id='table',
                         columns=[
                             {'name': 'ARC', 'id': 'ARC'},
                             {'name': 'Description', 'id': 'Description'},
                             {'name': 'Recommended', 'id': 'Recommended'},
                             {'name': 'Count_I', 'id': 'Count_I'},
                             {'name': 'Count_N', 'id': 'Count_N'},
                             {'name': 'Count_P', 'id': 'Count_P'},
                             {'name': 'Imp_percent', 'id': 'Imp_percent'}
                         ],
                         sort_action='native',  # Enables native sorting
                         sort_mode='multi',  # Allows multi-column sorting,
                         style_table={'overflowX': 'auto', 'margin-top': '20px'}
                         )
])

# Callback to update frequency table, plots, and table based on input SIC
@app.callback(
    [Output('output-plot-1', 'figure'),
     Output('output-plot-2', 'figure'),
     Output('table', 'data')],
    [Input('sic-input', 'value')]
)
def update_output(sic_input):
    if sic_input is None or sic_input not in ASSESS_df['SIC'].unique():
        return px.scatter(), px.scatter(), []  # Return default scatter plots if SIC is not valid

    # Filter DataFrame based on input SIC for Plot 1
    filtered_df_1 = ASSESS_df[ASSESS_df['SIC'] == sic_input][['EC_plant_usage']]
    filtered_df_1['EC_plant_usage'] = filtered_df_1['EC_plant_usage'].fillna(0).astype(int)
    quartiles_1 = filtered_df_1['EC_plant_usage'].quantile([1/3, 2/3, 1]).values
    # Plot for Plot 1
    fig_1 = px.histogram(
        filtered_df_1,
        x='EC_plant_usage',
        title='Frequency of Yearly electricity consumption (kWh)',
        opacity=0.7,
        barmode='overlay',
        color_discrete_sequence=['black'],
        marginal="box",
        hover_data=[filtered_df_1['EC_plant_usage']],
        range_x=[0, math.ceil(max(filtered_df_1['EC_plant_usage'] / 1000000)) * 1000000],
        nbins=len(range(0, math.ceil(max(filtered_df_1['EC_plant_usage'] / 1000000)) * 1000000, 1000000))
    )

    fig_1.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    binsize = 1000000
    frequency_table_1 = pd.cut(filtered_df_1['EC_plant_usage'], bins=range(0, filtered_df_1['EC_plant_usage'].max() + binsize, binsize))
    frequency_counts_1 = frequency_table_1.value_counts().sort_index()
    max_count_1 = frequency_counts_1.max()
    # Add shaded regions for every 33%
    fig_1.add_shape(
        type='rect',
        x0=0,
        x1=quartiles_1[0],
        y0=0,
        y1=1.3 * max_count_1,
        fillcolor='rgba(39,43,84, 0.5)',
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )
    fig_1.add_shape(
        type='rect',
        x0=quartiles_1[0],
        x1=quartiles_1[1],
        y0=0,
        y1=1.3 * max_count_1,
        fillcolor='rgba(195,46,91, 0.5)',
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )
    fig_1.add_shape(
        type='rect',
        x0=quartiles_1[1],
        x1=math.ceil(int(quartiles_1[2]) / 1000000) * 1000000,
        y0=0,
        y1=1.3 * max_count_1,
        fillcolor='rgba(235,125,39, 0.5)',
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    for q, label, color in zip(quartiles_1[:2], ['33%', '66%'], [(239, 227, 2), (126, 201, 76)]):
        fig_1.add_annotation(
            x=q,
            y=max_count_1,
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )

    # Filter DataFrame based on input SIC for Plot 2
    filtered_df_2 = ASSESS_df[ASSESS_df['SIC'] == sic_input][['E2_plant_usage']]
    filtered_df_2['E2_plant_usage'] = filtered_df_2['E2_plant_usage'].fillna(0).astype(int)
    quartiles_2 = filtered_df_2['E2_plant_usage'].quantile([1/3, 2/3, 1]).values
    # Plot for Plot 2
    fig_2 = px.histogram(
        filtered_df_2,
        x='E2_plant_usage',
        title='Frequency of Yearly natural gas consumption (MMBtu)',
        opacity=0.7,
        barmode='overlay',
        color_discrete_sequence=['black'],
        marginal="box",
        hover_data=[filtered_df_2['E2_plant_usage']],
        range_x=[0, math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000],
        nbins=len(range(0, math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000, 1000))
    )
    fig_2.update_traces(marker_line_color='black', marker_line_width=1)  # Add black outline to bins
    binsize = 1000
    frequency_table_2 = pd.cut(filtered_df_2['E2_plant_usage'], bins=range(0, filtered_df_2['E2_plant_usage'].max() + binsize, binsize))
    frequency_counts_2 = frequency_table_2.value_counts().sort_index()
    max_count_2 = frequency_counts_2.max()
    # Add shaded regions for every 33%
    fig_2.add_shape(
        type='rect',
        x0=0,
        x1=int(quartiles_2[0]),
        y0=0,
        y1=1.3 * max_count_2,
        fillcolor='rgba(39,43,84, 0.5)',
        line=dict(color='rgba(39,43,84, 0.5)', width=2)
    )
    fig_2.add_shape(
        type='rect',
        x0=int(quartiles_2[0]),
        x1=int(quartiles_2[1]),
        y0=0,
        y1=1.3 * max_count_2,
        fillcolor='rgba(195,46,91, 0.5)',
        line=dict(color='rgba(195,46,91, 0.5)', width=2)
    )
    fig_2.add_shape(
        type='rect',
        x0=int(quartiles_2[1]),
        x1=int(math.ceil(max(filtered_df_2['E2_plant_usage'] / 1000)) * 1000),
        y0=0,
        y1=1.3 * max_count_2,
        fillcolor='rgba(235,125,39, 0.5)',
        line=dict(color='rgba(235,125,39, 0.5)', width=2)
    )
    for q, label, color in zip(quartiles_2[:2], ['33%', '66%'], [(239, 227, 2), (126, 201, 76)]):
        fig_2.add_annotation(
            x=q,
            y=max_count_2,
            text=label,
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-40,
            font=dict(color=f'rgb{color}')
        )

    filtered_df_3 = ISADS[ISADS['SIC'] == 1221]
    filtered_df_3['Count_N'] = filtered_df_3['IMPSTATUS'].copy()
    filtered_df_3['Count_P'] = filtered_df_3['IMPSTATUS'].copy()
    filtered_df_3 = filtered_df_3.groupby('ARC2').agg({
        'ID': 'count',
        'Description': 'first',
        'SIC': 'first',
        'IMPSTATUS': lambda x: (x == 'I').sum(),
        'Count_N': lambda x: (x == 'N').sum(),
        'Count_P': lambda x: (x == 'P').sum()
    }).reset_index()
    filtered_df_3.rename(columns={'ID': 'Recommended', 'ARC2': 'ARC', 'IMPSTATUS': 'Count_I'}, inplace=True)
    filtered_df_3['Imp_percent'] = round(filtered_df_3['Count_I'] * 100 / (filtered_df_3['Count_I'] + filtered_df_3['Count_N']), 2)
    tab = filtered_df_3[['ARC', 'Description', 'Recommended', 'Count_I', 'Count_N', 'Count_P', 'Imp_percent']].copy()
    tab.sort_values(by='Imp_percent', ascending=False, inplace=True)
    table_data = tab.to_dict('records')

    return fig_1, fig_2, table_data

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

/Users/tm37384/anaconda3/lib/python3.11/site-packages/dash/resources.py:61: UserWarning:

You have set your config to `serve_locally=True` but A local version of https://codepen.io/chriddyp/pen/bWLwgP.css is not available.
If you added this file with `app.scripts.append_script` or `app.css.append_css`, use `external_scripts` or `external_stylesheets` instead.
See https://dash.plotly.com/external-resources

/var/folders/n7/ssh68f691_ldtyjm0gws54b0mz760s/T/ipykernel_48920/365941150.py:188: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/n7/ssh68f691_ldtyjm0gws54b0mz760s/T/ipykernel_48920/365941150.py:189: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy